### ISSUE TITLE
Single-User page goes blank when switching browser tabs

### ISSUE THREAD

**Issue by Zackrobat** [AdamSandstedt/Crumble-Online#22]
Hi,

In Chrome on Linux, when I play against the AI and switch to another browser tab and then back to the game, the page is blank white until the AI finishes thinking. I would expect to see the current game position.

Be well,
Zack

**Comment by AdamSandstedt** [comment]
I updated it so the ai doesn't block the rest of the javascript. It slows down the AI a bit but it should solve this issue. Let me know if this is still happening
