### ISSUE TITLE
Create an AI that you can play against in a single-player mode

### ISSUE THREAD

**Issue by AdamSandstedt** [AdamSandstedt/Crumble-Online#7]

**Comment by AdamSandstedt** [comment]
I added an AI but it could definitely use some more work. I also still need to update new.php to allow the user to select which color the AI plays as (it's just hardcoded to white for now). I also need to update my-games.php to point to single-player.php instead of two-player.php if the current local game is against the AI

**Comment by Zackrobat** [comment]
It's a great start! The AI is already strong enough that newcomers will have a good opponent.

I suspect it will be very difficult to add awareness of imperviousness, redundancy, and destiny without slowing the whole thing down by a huge amount.

But a rudimentary understanding of 'whip' renewables might be an easy way to increase the playing strength without a big speed hit. For example, the larger the size of the swappable region attacked by a renewable, the more value that renewable has for the position.

**Comment by AdamSandstedt** [comment]
I fixed the issues I mentioned in my first comment so I'm pretty happy with where the AI is at for now. I might come back and try to improve it at some point though.
If the AI were able to search deeper into the game tree, I bet it would be able to figure out imperviousness on its own and maybe renewables too. So, I think the biggest improvement to the AI would just be to optimize how fast it can make moves and copy game states.
